# Use root/example as user/password credentials
version: '3.1'

services:

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: [password]
    volumes:
      - mysql-data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9876:8080
volumes:
  mysql-data:
    driver: local
